### PR TITLE
#9: fixed genpot warnings by assigning names

### PR DESCRIPTION
**Pull request by EmilyOng**
Hello!

With regard to #9, I tried to assign names to the string formatters so instead of `%s` it would be something like `%(debitTotal)s`, and this removed the translation problem.

### CODE REVIEW

**Comment by walterbender** [comment]
This looks like it resolves the issue. But it would be nice to not use JavaScript style camelCase in Python, so rather than creditTotal, use credit_total, etc.

**Comment by walterbender** [comment]
Also, please make sure the indentation passes pylint.

**Comment by walterbender** [comment]
C:515, 0: Line too long (112/100) (line-too-long)
C:516, 0: Wrong continued indentation (add 28 spaces).
                                      'credit_count': credit_count}))
                                      ^                           | (bad-continuation)
C:519, 0: Line too long (107/100) (line-too-long)
C:520, 0: Wrong continued indentation (add 26 spaces).
                                     'debit_count': debit_count}))
                                     ^                         | (bad-continuation)

**Comment by quozl** [comment]
Agreed.  Another way to check is with flake8;

```
$ python -m flake8 *.py
finance.py:515:80: E501 line too long (112 > 79 characters)
finance.py:516:39: E128 continuation line under-indented for visual indent
finance.py:519:80: E501 line too long (107 > 79 characters)
finance.py:520:38: E128 continuation line under-indented for visual indent
finance.py:979:80: E501 line too long (93 > 79 characters)
```

You can ignore E402 from flake8; and I've been adding a `.flake8` file occasionally, see Paint activity.

**Comment by EmilyOng** [comment]
Thanks @walterbender  and @quozl, I have ensured that the indentation and length of the code adheres to the pep8 style guide. pylint and flake8 have been really useful... didnt use to know much about having maintainable and style adherence code for python. In the process, I have also chanced upon autopep8, which I thought would be quite useful

**Pull request closed without merging**
