### PR TITLE
Restrict input in Amount column

### LINKED ISSUE #23: Restrict input in Amount column.
The amount column even takes alphabets as an input which results in the following traceback 
```
Traceback (most recent call last):
  File "/home/aniket/activities/finance-activity/registerscreen.py", line 171, in amount_edit_cb
    t['amount'] = abs(locale.atof(new_text))
  File "/usr/lib/python2.7/locale.py", line 318, in atof
    return func(string)
ValueError: could not convert string to float: sadad
```

### PR DESCRIPTION
**Pull request by ayushnawal**
Fixes #23 
@Aniket21mathur please review!

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  As `'12.34'.isdigit()` evaluates to `False`, this change would prevent most real-life currency inputs, instead setting them to zero. Did you really test this?

Also, why is zero an appropriate value to use when the input is invalid?

@sanjay237 did recently [add expression input](https://github.com/sugarlabs/chart/commit/578e1a29d2cef6a0a6e66c4421c48764033bdf03) to the Chart activity.  Given that improvement, wouldn't it make more sense to add expression input to Finance as well?

**Comment by ayushnawal** [comment]
Fixed.
Added expression input also. 

>Also, why is zero an appropriate value to use when the input is invalid? 

We need to set the input to zero when the input is invalid because all the rows of visible transactions are added or subtracted in `update_summary()`, as we know that zero has no effect on addition/subtraction. the most appropriate choice is zero.

**Comment by ayushnawal** [comment]
@srevinsaju did the same for the budget page too. everything is looking good now!

**Comment by srevinsaju** [comment]
Perfect @ayushnawal , we will wait for @quozl to review, I might have missed out something :)

**Comment by quozl** [comment]
Thanks.  Reviewed.  I don't agree with the reasoning on using zero.

* [ ] when an invalid expression is input, do not change it to zero; instead either (a) do not accept the entry (and optionally change the entry background to yellow like how Poll does it), or (b) leave the value unchanged (and optionally give an Alert explaining that the expression was invalid),

Also the pull request branch is old;

* [ ] please pull and rebase, as I had already fixed the SyntaxWarning on the _master_ branch, see https://github.com/sugarlabs/finance-activity/commit/abcb1a519efe863d581463fd28d7e987429a6f3a,

**Comment by quozl** [comment]
Also, there's a lot of code added twice.  Add a new file for it.  Even better if the same file is added to Chart.

**Comment by srevinsaju** [comment]
@ayushnawal, try codacy and analyzing your code, and see the grade you get on it, A is good, B needs to be improved, etc.. codacy checks for repetition of code too

**Comment by quozl** [comment]
:laughing: easier to look at the aggregate change and think "oy, i just saw that!"

**Comment by ayushnawal** [comment]
* rebased
* input remains unchanged on invalid input
* added a separate file for extracting input

regarding the optional part of adding an alert box, I am opening an improvement bug issue, for now, I will look back at it again but i need to finish other remaining PRs first.

Thanks :grin:

**Comment by ayushnawal** [comment]
woohoo! .. forgot about the `Alert` tool.
fixed it now :rocket:
@quozl PR is ready from my side now :grin:

**Comment by quozl** [comment]
Thanks.  Reviewed.  Added commits instead of listing what I'd like changed.  Tested.  Several combinations did not work, so added further commits.  Left to be done is;

* [ ] the expression `4*-4` does not work, and I'm not sure why,
* [ ] there's a ZeroDivisionError in logs now that zero is an allowed budget value; my guess is that this was never expected or allowed, but a zero budget is not an impossibility in accountancy (my degree was business, so in theory i'm qualified :grin:),

**Comment by ayushnawal** [comment]
@quozl 

Fixed ZeroDivisionError. Set budget to `10**-9` as it is v. close to zero, so the ratio will be set accordingly, hence `cr.set_source_rgb` and `cr.line_to` will be working fine in all practical cases.

Regarding the expression `4*-4`, for now, the fix will display invalid value alert for it instead of the traceback, unfortunately since we have used external package that was also used in chart activity, i can't find a fix for now, if you wish i will open an issue for such expressions.

**Comment by quozl** [comment]
Okay, thanks.  That way of handling a division by zero is pretty strange.  Also, best to check against zero rather than just `if budget`.

@sanjay237, as @ayushnawal has declared disinterest, have you any idea how to handle the expression `4*-4` properly?

**Comment by ayushnawal** [comment]
> That way of handling a division by zero is pretty strange

Bit strange :grimacing: but It will work in almost all practical cases since zero was not handled before also.

> as @ayushnawal has declared disinterest, have you any idea how to handle the expression 4*-4 properly?

I didn't declare any disinterest :sweat_smile: , I was thinking of a basic algorithm using stack for evaluating expressions but I need time for that and changes made by @sanjay237 is an improvement for now.
Opened #26 

Also, we can now close #23

**Comment by sanjay237** [comment]
@ayushnawal @quozl Thanks for asking. I've raised a PR towards that [here](https://github.com/sugarlabs/finance-activity/pull/27). Here's a gist; 

We evaluate the AST tree with operations that are a) recognized by the module and b) have their operations defined in our parser.

Instances that only used binary operations worked okay, but instances with unary operations (like 4*-4, which had a negation operation, crashed). The unary operator was recognized by the module (passed _a_), but was not defined in our parser (failed _b_).

This was expected. Charts raised an error when this happened, I feel this should too.

I've added a unary operator (negation) to pass _b_ now.

> I was thinking of a basic algorithm using stack for evaluating expressions but I need time for that and changes made by @sanjay237 is an improvement for now.

Do you have a particular shortcoming of this method in mind? Happy to help if I can :)

> - [ ]  the expression 4*-4 does not work, and I'm not sure why,

Hope I gave an okay explanation 😅

**Comment by quozl** [comment]
Replaced by https://github.com/sugarlabs/finance-activity/pull/27

**Pull request closed without merging**
