### PR TITLE
Undo-Redo Feature

### PR DESCRIPTION
**Pull request by ryan-van**
[Completed] add undo and redo buttons, covering changes to the register; new rows, column edits, and row deletions,
[Completed] maintain a separate undo and redo stack for the budget screen,
[More information please] show an abstraction of the next undo or redo operation in the tooltips of the buttons,
[Completed] use the EditToolbar and UndoButton classes from the Sugar Toolkit, as these provide a familiar pattern and the ctrl+z accelerator for undo,

Per Issue #29 I completed and tested the Undo and Redo feature being added to the Finance-Activity. I tested with the test data set as well as with adding columns and editing them myself. Some of the things I did to test:

- Added blank column, undo deletes, redo places it back. 
- Did the same for column with information, information persists.
- Tested Undo --> Change something --> Redo doesn't work
- 50 Deletes --> 50 Redos, no errors, works as intended.

I believe the pull request should be mostly done, other than "show an abstraction of the next undo or redo operation". Could you elaborate more on this? I feel like it may be hard to show what the next operation will do, other than the undo / redo already being there. 

Also, I have been working by pushing onto Github and pulling on a VM for the Sugar Hybrid Build and I have many commits because of this. I couldn't get the environment set-up on Windows to run (will be working on this).

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Great work.  Tested;

* [ ] the undo and redo buttons are sensitive even if there is nothing to undo or redo,
* [ ] undo of a transaction add worked, but the redo afterwards did not, when using the FINANCE_TEST data set,
* [ ] the scrolled area changes position when undo or redo is pressed; perhaps `build_screen` should only be called if needed.

**Comment by ryan-van** [comment]
Hey @quozl  I reviewed what you talked about.

- For the sensitivity of the buttons, I assumed it would be a property of the widgets.py or ToolButton class for the hover ability, but I couldn't find anything concerning this (even looking through documentation for GTK.ToolButton). Do you know where I can look into this? I assume this should be an easy fix if the property does exist.

- It looks like for the undo/redo's of the beginning the data set is leaking over into April/May because of the way the test data set is made. I believe if you change the month view to May and then undo/redo, it works for me. Let me know if it isn't replicable for you.

- For the scroll area being changed I believe it's because of the date that it's being added. It's being added as the current date and the screen isn't being rebuilt until the undo is called, in which the transaction moves to the correct place. This shouldn't be a problem for regular users as they shouldn't have transactions taking place after the current date.

Let me know if there's anything I can work on here. Thanks!

**Comment by quozl** [comment]
Sorry for the delay.

> Hey @quozl I reviewed what you talked about.
> 
>  * For the sensitivity of the buttons, I assumed it would be a property of the widgets.py or ToolButton class for the hover ability, but I couldn't find anything concerning this (even looking through documentation for GTK.ToolButton). Do you know where I can look into this? I assume this should be an easy fix if the property does exist.

Sure.  Call [`Gtk.Widget.set_sensitive`](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Widget.html#Gtk.Widget.set_sensitive).

>  * It looks like for the undo/redo's of the beginning the data set is leaking over into April/May because of the way the test data set is made. I believe if you change the month view to May and then undo/redo, it works for me. Let me know if it isn't replicable for you.

Thanks.

>  * For the scroll area being changed I believe it's because of the date that it's being added. It's being added as the current date and the screen isn't being rebuilt until the undo is called, in which the transaction moves to the correct place. This shouldn't be a problem for regular users as they shouldn't have transactions taking place after the current date.
> 
> Let me know if there's anything I can work on here. Thanks!

The undo or redo could return a boolean to say if they have made a change.

**Comment by ryan-van** [comment]
@quozl Thanks for the review again! I worked on getting the sensitives button. Tested it w/ random transactions and finance_test, seems to be working fine. Added boolean returns for functions and cleaned up code to use more functions rather than hard coding.

**Comment by ryan-van** [comment]
@quozl Can you review the update? Thanks!

**Comment by quozl** [comment]
Thanks.  Tested.  Looks great.

**Comment by quozl** [comment]
I've tried rebasing by hand and the conflicts were extensive and I got bored.  The point of divergence was the rebasing of the previous pull request.  I rewrote the commits and rebased by hand.  Next time could you please rebase your _master_ on our _master_, and then rebase this pull request branch?  Merged as 18c1ff5.

**Comment by ryan-van** [comment]
Yes, I'll definitely do that next time. Still trying to get a handle on open source git. Thanks for reviewing!

**Comment by quozl** [comment]
Thanks.  You can practice if you'd like; you can checkout https://github.com/sugarlabs/finance-activity/pull/34/commits/d0272db790a45e804a97c3c30915be4ce8cdd4b9 as a new branch and figure out how to rebase.

Since this pull request affected only three files, the simplest method I found was;

```log
git checkout master   # my master was same as sugarlabs master
git fetch sugarlabs pull/34/head  # get the commits from the pull request
git checkout d0272db -- README.md finance.py registerscreen.py  # get the files
git commit --author "Ryan Van <ryan.van@berkeley.edu>"
```

The worst method seemed to be to use `git rebase`. :grin:

**Pull request closed without merging**
